from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)
from reportlab.lib.styles import (
    getSampleStyleSheet
)
from reportlab.lib import colors
from reportlab.platypus.tables import (
    Table,
    TableStyle
)
import os
def generate_pdf(
    company_name,
    report_content
):
    os.makedirs(
        "app/generated_reports",
        exist_ok=True
    )
    pdf_path = (
        f"app/generated_reports/{company_name}.pdf"
    )
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=30
    )
    styles = getSampleStyleSheet()
    story = []
    title = Paragraph(
        f"""
        <font size=22>
        <b>{company_name} AI Business Audit Report</b>
        </font>
        """,
        styles["Title"]
    )
    story.append(title)
    story.append(
        Spacer(1, 25)
    )
    table_data = [
        ["Company Name", company_name],
        ["Generated By", "AI Lead Automation System"],
        ["Report Type", "AI Business Audit"],
    ]
    table = Table(
        table_data,
        colWidths=[180, 300]
    )
    table.setStyle(
        TableStyle([
            ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
            ("TEXTCOLOR", (1, 0), (1, -1), colors.black),
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#2563eb")),
            ("GRID", (0, 0), (-1, -1), 1, colors.gray),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ])
    )
    story.append(table)
    story.append(
        Spacer(1, 30)
    )
    formatted_content = report_content.replace(
        "\n",
        "<br/><br/>"
    )
    content = Paragraph(
        f"""
        <font size=11>
        {formatted_content}
        </font>
        """,
        styles["BodyText"]
    )
    story.append(content)
    story.append(
        Spacer(1, 30)
    )
    footer = Paragraph(
        """
        <font size=10 color='gray'>
        Generated using AI Lead Automation Platform
        </font>
        """,
        styles["Normal"]
    )
    story.append(footer)
    doc.build(story)
    return pdf_path